# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bop < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/delightfulhammers/bop"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/delightfulhammers/bop/releases/download/v0.7.1/bop_0.7.1_darwin_amd64.tar.gz"
      sha256 "86c7cb584bf2eb41cf8597c9691c58e97bc4e75f39d34a6d66867b3eaf28a5c2"

      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/delightfulhammers/bop/releases/download/v0.7.1/bop_0.7.1_darwin_arm64.tar.gz"
      sha256 "944ac67ccb0ec793df569ba8d7990d84e7e4f750f17b9b9202289f6761d60dd2"

      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/bop/releases/download/v0.7.1/bop_0.7.1_linux_amd64.tar.gz"
      sha256 "c5b3b6d2c4eecc7a74c6d6658b3f60559d9088180098259b8108e86ea8145fdf"
      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/bop/releases/download/v0.7.1/bop_0.7.1_linux_arm64.tar.gz"
      sha256 "db4ef0394e5263f9a12e0bdd69f606e2c8c18ff95cc64daac61c04b71023b960"
      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use bop, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        bop review branch main

      For GitHub PR integration:
        export GITHUB_TOKEN="your-token"
        bop review branch main --github-post --pr 123
    EOS
  end

  test do
    system "#{bin}/bop", "version"
  end
end
