# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bop < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/delightfulhammers/bop"
  version "0.12.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.12.4/bop_0.12.4_darwin_amd64.tar.gz"
      sha256 "69df35be67ec0c4944ff7f3de1f8d80d2c6056d0a136f35aab7931525fbc706e"

      define_method(:install) do
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.12.4/bop_0.12.4_darwin_arm64.tar.gz"
      sha256 "bfba9009d5a1725cf2256c3938bf915d0ef347bff74e6def37c4684641414c91"

      define_method(:install) do
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.12.4/bop_0.12.4_linux_amd64.tar.gz"
      sha256 "5e00744e91bbea651c977df8e7cd4f09258a3989f41a6cefee96ddd94e72c237"
      define_method(:install) do
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.12.4/bop_0.12.4_linux_arm64.tar.gz"
      sha256 "5076bad80c0fabcd8ad97efc001e086bf358933e0ef86d36b01757edd562475e"
      define_method(:install) do
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use bop, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        bop review branch main

      Review a GitHub PR (with posting):
        export GITHUB_TOKEN="your-token"
        bop review pr owner/repo#123 --post
        bop review pr 123 --post              # Infers owner/repo from git remote
    EOS
  end

  test do
    system "#{bin}/bop", "version"
  end
end
