# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bop < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/delightfulhammers/bop"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.11.1/bop_0.11.1_darwin_amd64.tar.gz"
      sha256 "790dd6dc65d742bba01ab27c14ea274dada82f075a0d05a4a23edd52b83f0639"

      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.11.1/bop_0.11.1_darwin_arm64.tar.gz"
      sha256 "8524bb97b901d106e28e29d0441f9d916a230fc07a7a850f10f8cd70bade8cc9"

      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.11.1/bop_0.11.1_linux_amd64.tar.gz"
      sha256 "2e00af359dc4bbdec7ec90c7894f2726d30be68f491b74ebaa908effab496580"
      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/delightfulhammers/homebrew-tap/releases/download/v0.11.1/bop_0.11.1_linux_arm64.tar.gz"
      sha256 "b924559bf994679c2d7c7679769a58df06ea6f181e0d0b4b0a7611b9619fed23"
      def install
        bin.install "bop"
        bin.install "bop-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use bop, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        bop review branch main

      Review a GitHub PR (with posting):
        export GITHUB_TOKEN="your-token"
        bop review pr owner/repo#123 --post
        bop review pr 123 --post              # Infers owner/repo from git remote
    EOS
  end

  test do
    system "#{bin}/bop", "version"
  end
end
