# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeReviewer < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/bkyoung/code-reviewer"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.1/code-reviewer_0.6.1_darwin_amd64.tar.gz"
      sha256 "0cbde0c97b94f74790ed882ad0914ed3f43b5611ed359880240df8c581249b85"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.1/code-reviewer_0.6.1_darwin_arm64.tar.gz"
      sha256 "ac0ff449c3b0f59d5038c706cb4573f1d76ed45ec2c6d0c048e66837f1d8b74a"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.1/code-reviewer_0.6.1_linux_amd64.tar.gz"
      sha256 "a824eaa72bcc13889be72255b72bc8f56d8e0a585c293da27b7296731e31cac5"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.1/code-reviewer_0.6.1_linux_arm64.tar.gz"
      sha256 "f501b0c7145f6bfa8b1592abd78b45c7811be69e5056bebfa9b770f80908e601"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use code-reviewer, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        cr review branch main

      For GitHub PR integration:
        export GITHUB_TOKEN="your-token"
        cr review branch main --github-post --pr 123
    EOS
  end

  test do
    system "#{bin}/cr", "version"
  end
end
