# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeReviewer < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/bkyoung/code-reviewer"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.0/code-reviewer_0.6.0_darwin_amd64.tar.gz"
      sha256 "08c01984d9c3d8eadbcea3dd416fe05dd4d5db9efa49b8defd0000efa488f92f"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.0/code-reviewer_0.6.0_darwin_arm64.tar.gz"
      sha256 "ef43c25f82ebad5499df2f8c5daf433b7d91e7e73eff5835cac00514eee3ab82"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.0/code-reviewer_0.6.0_linux_amd64.tar.gz"
      sha256 "85989a6ccc7f407f5dd7e7d5d4785ac947c25ca30da889597f62adfb2bb79544"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.6.0/code-reviewer_0.6.0_linux_arm64.tar.gz"
      sha256 "ef5bf4fdb328472ad8c2d456e83286dc5507693350be3e50ba5eb862a914423b"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use code-reviewer, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        cr review branch main

      For GitHub PR integration:
        export GITHUB_TOKEN="your-token"
        cr review branch main --github-post --pr 123
    EOS
  end

  test do
    system "#{bin}/cr", "version"
  end
end
