# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeReviewer < Formula
  desc "AI-powered code review tool with multi-provider LLM support"
  homepage "https://github.com/bkyoung/code-reviewer"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.5.2/code-reviewer_0.5.2_darwin_amd64.tar.gz"
      sha256 "9053ae46ac0c8c45ef3256e61d292c318de36b9d531d8ce08a1b19bd089e982f"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.5.2/code-reviewer_0.5.2_darwin_arm64.tar.gz"
      sha256 "cc3aa2ac64c614dcd298df6d6ce1ebba8c8c018f4842b3d6a88b97c282233415"

      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.5.2/code-reviewer_0.5.2_linux_amd64.tar.gz"
      sha256 "7547c8b86618bfa2d9f3f020796232950f0550344358bdfc741c915b398183a4"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkyoung/code-reviewer/releases/download/v0.5.2/code-reviewer_0.5.2_linux_arm64.tar.gz"
      sha256 "3f08446775d22dff8fc1d2262e7ad7ef0504c71257074ffcd1bb34001df3f394"
      def install
        bin.install "cr"
        bin.install "code-reviewer-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To use code-reviewer, set at least one LLM provider API key:
        export ANTHROPIC_API_KEY="your-key"    # Claude models
        export OPENAI_API_KEY="your-key"       # GPT models
        export GEMINI_API_KEY="your-key"       # Gemini models

      Quick start:
        cr review branch main

      For GitHub PR integration:
        export GITHUB_TOKEN="your-token"
        cr review branch main --github-post --pr 123
    EOS
  end

  test do
    system "#{bin}/cr", "version"
  end
end
